# Generated by Django 4.2.6 on 2023-10-14 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcontacts',
            name='lhw_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_contacts', to='dashboard.lhw_info'),
        ),
        migrations.CreateModel(
            name='ChildHealth2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_newborns_weighted', models.PositiveIntegerField(default=0)),
                ('no_low_birth_weight_babies', models.PositiveIntegerField(default=0)),
                ('no_newborn_started_breast_feeding', models.PositiveIntegerField(default=0)),
                ('no_newborn_applied_chlorhexidine', models.PositiveIntegerField(default=0)),
                ('no_newborn_immunization_started', models.PositiveIntegerField(default=0)),
                ('no_6_months_old_children', models.PositiveIntegerField(default=0)),
                ('no_6_months_old_children_exclusive_breast_feeding', models.PositiveIntegerField(default=0)),
                ('no_6_59_months_old_children', models.PositiveIntegerField(default=0)),
                ('no_6_59_months_old_children_mauc_done', models.PositiveIntegerField(default=0)),
                ('no_6_59_months_children_malnutrition_mauc', models.PositiveIntegerField(default=0)),
                ('no_6_59_months_children_malnutrition_less_than_mauc', models.PositiveIntegerField(default=0)),
                ('no_12_23_months_old_children', models.PositiveIntegerField(default=0)),
                ('no_12_23_months_old_children_fully_immunized', models.PositiveIntegerField(default=0)),
                ('no_5_years_children', models.PositiveIntegerField(default=0)),
                ('no_5_years_children_micro_nutrition_sachet', models.PositiveIntegerField(default=0)),
                ('no_5_years_children_gm_done_recorded', models.PositiveIntegerField(default=0)),
                ('no_5_years_children_low_weight', models.PositiveIntegerField(default=0)),
                ('lhw_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_health', to='dashboard.lhw_info')),
            ],
        ),
    ]
