# Generated by Django 4.2.6 on 2023-10-14 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_socialcontacts_lhw_code_childhealth2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChildHealth2',
            new_name='ChildHealth',
        ),
    ]
