# Generated by Django 4.2.6 on 2023-10-14 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_childhealth2_childhealth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherhealth',
            name='lhw_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_health', to='dashboard.lhw_info'),
        ),
    ]
