# Generated by Django 4.2.6 on 2023-11-11 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_motherhealth_lhw_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervision',
            name='lhw_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision', to='dashboard.lhw_info'),
        ),
    ]
