# Generated by Django 4.2.6 on 2023-11-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_supervision_lhw_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supervision',
        ),
    ]
