# Generated by Django 4.2.6 on 2023-11-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_delete_supervision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_visits_by_lhs', models.PositiveIntegerField(default=0, verbose_name='No of visits by LHS')),
                ('no_of_visits_by_dco_np', models.PositiveIntegerField(default=0, verbose_name='No of Visit by DCO (NP)')),
                ('no_of_visits_by_adc_np', models.PositiveIntegerField(default=0, verbose_name='No of Visit by ADC (NP)')),
                ('no_of_visits_by_fpo', models.PositiveIntegerField(default=0, verbose_name='No of Visit by FPO')),
                ('no_of_visits_by_ppiu', models.PositiveIntegerField(default=0, verbose_name='No # of Visit by PPIU')),
                ('lhw_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervision', to='dashboard.lhw_info')),
            ],
        ),
    ]
