# Generated by Django 4.2.6 on 2024-01-23 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_supervision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyplanning',
            name='lhw_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_planning', to='dashboard.lhw_info'),
        ),
    ]
