# Generated by Django 4.2.6 on 2024-01-23 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_familyplanning_lhw_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthsdeaths',
            name='lhw_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_deaths', to='dashboard.lhw_info'),
        ),
    ]
